### ISSUE TITLE
Results with too many Floaters

### ISSUE THREAD

**Issue by pigtigger** [gsgen3d/gsgen#11]
<img width="786" alt="image" src="https://github.com/gsgen3d/gsgen/assets/39974202/4f1106a5-ea98-4656-9ece-4c91a4e0658f">
Congrats on your great work!
I have tried the corgi sample using your code, but there are too many floaters in the results, I didn't change anything, can you give me some advice?

**Comment by haodong2000** [comment]
I am also curious about it, cause I have not met such situation after running 20+ cases of GEGEN. What is your prompt and init.prompt?

**Comment by pigtigger** [comment]
```shell
python main.py --config-name=base wandb=False batch_size=1 prompt.prompt="A high quality photo of a corgi" init.prompt="a corgi" init.mean_std=1.0 +disable_warnings=True
``` 
I just run this corgi command.

**Comment by haodong2000** [comment]
> ```shell
> python main.py --config-name=base wandb=False batch_size=1 prompt.prompt="A high quality photo of a corgi" init.prompt="a corgi" init.mean_std=1.0 +disable_warnings=True
> ```
> 
> I just run this corgi command.

`python main.py --config-name=base prompt.prompt="A high quality photo of a corgi" init.prompt="a corgi"`

![corgi_issue](https://github.com/gsgen3d/gsgen/assets/67775090/9199143a-dae4-4f58-933f-f5a1dc31856f)

**Comment by pigtigger** [comment]
@heheyas @haodong2000 thank you for your help！I will try bs=4.

**Comment by vvuonghn** [comment]
This is the result when I train using the command `python main.py --config-name=base prompt.prompt="a cute corgi"`|

Why does the dog have two heads?

https://github.com/user-attachments/assets/900621e4-eb85-49ea-b87d-bde5fc9ecd8e
