### ISSUE TITLE
LICENSE file? 

### ISSUE THREAD

**Issue by terrance-wang** [gsgen3d/gsgen#20]
I recently came across gsgen and was really impressed with its results. I can see that you guys have put a lot of effort into it, and I think it would be a valuable addition to a project I'm currently working on. However, I'm curious if this is code is viable for commercial or research use. Can you please clarify the terms of using this code with a LICENSE file to this repository? Thanks!

**Comment by heheyas** [comment]
License updated, thanks for noticing.

**Comment by terrance-wang** [comment]
thanks!
