### ISSUE TITLE
how long does a training session take

### ISSUE THREAD

**Issue by nemorix** [gsgen3d/gsgen#21]
great job!But I have a question, how long does a training session take, because it's been three days since I started training, but I'm still 

"will align the point cloud to the x axis.
will use random color". 

It's not clear to me what's going on.

**Comment by heheyas** [comment]
Hi nemorix,

Thanks for your interest. Can you see the progress bar in the terminal? If not, the training has not started, otherwise, there will be a progress bar indicating the speed and eta for training.

**Comment by nemorix** [comment]
Thanks for your reply, I just see some points in terminal  like this:
`Using Point-E on device: cuda
creating base model...
creating upsample model...
downloading base checkpoint...
downloading upsampler checkpoint...
will align the point cloud to the x axis
will use random color
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................`


And the number of points keeps increasing. I don’t know whether this means he is training or in the preparation stage.

**Comment by heheyas** [comment]
This indicates you cannot get access to huggingface, one `.` means a failed connection. Please refer to #17 for details.

**Comment by nemorix** [comment]
Thank you for your answer, this is very helpful for me, **** GFW🤬. I'm also sorry for not taking a closer look at the previous issue, which took up your time.
Best regards,
nemorix
