### ISSUE TITLE
About training results

### ISSUE THREAD

**Issue by ch1998** [gsgen3d/gsgen#27]
Excellent project.
The quality of the build is good, but the results don't seem that normal.
In the results I got, the corgi has 5 legs, is this normal?
![1700731760387](https://github.com/gsgen3d/gsgen/assets/37291486/db2bd848-e7c9-43b2-a58c-f5540a23fea2)

cmd used：
python main.py --config-name=base prompt.prompt="A high quality photo of a corgi" init.prompt="a corgi"

**Comment by KevinXu02** [comment]
Yes. As the training process is based on a single view each step and the basic sd model does not know the exact camera position, the generated object might have multi-heads or legs.
