### ISSUE TITLE
A small kind advice about `init.prompt` in `conf/base.yaml`

### ISSUE THREAD

**Issue by haodong2000** [gsgen3d/gsgen#8]
the `init.prompt` in `conf/base.yaml` should be set `None`, instead of _"a human face"_.

Currently text-to-3d algorithms are sensitive to initialization, and in 3D Gaussians, Point-E is often used. Here is an example: _"a DSLR photo of a corgi wearing a green suit and a top hat"_

`init.prompt = None`
![corgi_0](https://github.com/gsgen3d/gsgen/assets/67775090/8c4518ce-bf7f-4e28-af6e-50be1b24abb5)

`init.prompt = a dog`
![corgi_dog](https://github.com/gsgen3d/gsgen/assets/67775090/b58b4611-3a31-4c41-b8e3-dea9210b1651)

`init.prompt = a corgi`
![corgi_corgi](https://github.com/gsgen3d/gsgen/assets/67775090/43918725-e531-44d2-8af3-b2953b4e7a45)

**Comment by heheyas** [comment]
Hi haodong,

Thanks for your interest. You are right. The `a human face` in the config is the initialing prompt for `A highly detailed stone bust of Theodoros Kolokotronis`. I will fix this issue in the next commit. Thanks for your help. I will mark this issue as completed, and feel free to reopen it if you have other concerns.

Best regards,
heheyas
